// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IPageFields {
  /** Internal name */
  name: string

  /** Page title */
  title: string

  /** Slug */
  slug: string

  /** SEO metadata */
  seo?: ISeo | undefined

  /** Body */
  body?: Document | undefined
}

/** Represents a web page. */

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'page'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ISeoFields {
  /** Internal name */
  name: string

  /** SEO title */
  title?: string | undefined

  /** Description */
  description?: string | undefined

  /** Keywords */
  keywords?: string[] | undefined

  /** Hide page from search engines (noindex) */
  no_index?: boolean | undefined

  /** Exclude links from search rankings? (nofollow) */
  no_follow?: boolean | undefined

  /** Display title */
  displayTitle?: string | undefined
}

/** SEO Metadata for web pages in Compose. DO NOT DELETE */

export interface ISeo extends Entry<ISeoFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'seo'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITextFields {
  /** Общи условия */
  text?: Document | undefined
}

export interface IText extends Entry<ITextFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'text'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'page' | 'seo' | 'text'

export type LOCALE_CODE = 'bg' | 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
